### ISSUE TITLE
dist/commonjs should output ES5 since dist/module outputs ES6+

### ISSUE THREAD

**Issue by bmakuh** [chriskrycho/true-myth#12]
Currently the transpiled code in dist/commonjs contains things like `const` that signify that it is not being transpiled all the way down to ES5.

Currently this is causing our build pipeline to break.

**Comment by chriskrycho** [comment]
@bmakuh ugh, sorry about that.

What are your thoughts on the approach in #10, i.e. "just use [@std/esm](https://github.com/standard-things/esm) for CommonJS"?

**Comment by bmakuh** [comment]
So unfortunately, we're still on webpack 1, which means that while we can use `import` syntax, we are still stuck with commonjs modules. I'm hoping to rectify that soon, but you know, Rails.

I haven't personally investigated @std/esm myself, but after reading through your explanation it makes sense. The one thing it seems like it would preclude, though, is the possibility of using T-M with legacy systems (like ours is currently 🙈) or without a build system. I don't know if that's enough of a sticking point though. What do you think?

**Comment by chriskrycho** [comment]
I'm back and forth on this. Obviously that branch has sat open for a while. I *do* dislike that the current setup adds extra work for anyone who wants to consume via Node or ts-node. 😖

**Comment by chriskrycho** [comment]
Closing this because in the meantime Node bumped LTS to v6, which has full support for all ES6 constructs, and I think tracking Node LTS is the best support policy.
